# Header
menu:
  - label: 关于我
    href: /about.html
    target: _self

  - label: 文章归档
    href: /archives.html
    target: _self

  - label: github
    href: https://github.com/worklinwu
    target: _blank

  - label: <strong>HtmlConvertToCss</strong>
    href: http://www.linwu.name/HtmlConvertToCss
    target: _self

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false